# Generated by Django 5.0 on 2024-01-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xss_app', '0003_delete_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=30)),
                ('blog_post_text', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
