# Generated by Django 5.0 on 2024-01-30 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xss_app', '0004_blog_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blog_post_text',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='blog',
            name='headline',
            field=models.CharField(max_length=200),
        ),
    ]
