# Generated by Django 5.0 on 2024-04-24 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xss_app', '0006_alter_blog_author_alter_blog_content'),
        ('xss_app', '0007_alter_blog_pub_date'),
    ]

    operations = [
    ]
